---
title: Val er niet in!
hero_image: images/banner.png
description: Ontwerp en maak een hindernis- of platformparkour-spel met bovenaanzicht.
meta_title: Scratch-programmeerprojecten voor kinderen en tieners | Val er niet in
meta_description: Leer Scratch met de programmeerprojecten van de Raspberry Pi Foundation voor kinderen en tieners. Maak een parkour-spel en springen, huppelen, glijden, stuiteren of vliegen om een ritje te maken.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - 
    title: Wat ga je maken
  - 
    title: Kies je thema
  - 
    title: Spring, huppel, stuiter of glijd!
    completion:
      - engaged
  - 
    title: Winnaar
  - 
    title: Rijd op platforms
  - 
    title: Pas de moeilijkheidsgraad aan
    completion:
      - internal
  - 
    title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Verbeter je project
  - 
    title: Deel
  - 
    title: Wat kun je verder nog doen?
