title: "Don't fall in!"
hero_image: images/banner.png
description: Design and create a top-down view obstacle or platform parkour game.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Choose your theme
  - title: Jump, hop, bounce, or glide!
    completion: engaged
  - title: Winner
  - title: Ride on platforms
  - title: Adjust the difficulty
    completion: internal
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
    completion: external
  - title: Share
  - title: What next?
