---
title: Don't fall in!
hero_image: images/banner.png
description: Design and create a top-down view obstacle or platform parkour game.
meta_title: Scratch coding projects for kids and teens | Don't fall in
meta_description: Learn Scratch with the Raspberry Pi Foundation’s coding projects for kids and teens. Make a Scratch parkour game then jump, hop, or fly to catch a ride.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: What you will make
  - 
    title: Choose your theme
  - 
    title: Jump, hop, bounce, or glide!
    completion:
      - engaged
  - 
    title: Winner
  - 
    title: Ride on platforms
  - 
    title: Adjust the difficulty
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Challenge
    challenge: true
  - 
    title: Share
  - 
    title: What can you do now?
