---
title: Paid disgyn i mewn!
hero_image: images/banner.png
description: Dylunio a chreu gêm persbectif o'r brig neu blatfformiau parkour.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Byddi di'n creu
  - title: Dewis dy thema
  - title: Neidio, hopian, bownsio, neu gleidio!
    completion:
      - engaged
  - title: Enillydd
  - title: Reidio ar blatfform
  - title: Addasu lefel yr anhawster
    completion:
      - internal
  - title: Cwis cyflym
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Uwchraddio dy brosiect
  - title: Rhannu
  - title: Beth nesaf?
