---
title: '¡No te caigas!'
hero_image: images/banner.png
description: Diseña y crea un juego de parkour con obstáculos o plataformas con vista de arriba hacia abajo.
meta_title: Scratch coding projects for kids and teens | Don't fall in
meta_description: Learn Scratch with the Raspberry Pi Foundation’s coding projects for kids and teens. Make a Scratch parkour game then jump, hop, or fly to catch a ride.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - 
    title: Lo que harás
  - 
    title: Elige tu tema
  - 
    title: '¡Salta, brinca, rebota o deslízate!'
    completion:
      - engaged
  - 
    title: Ganador
  - 
    title: Sube plataformas
  - 
    title: Ajusta la dificultad
    completion:
      - internal
  - 
    title: Examen rápido
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Mejora tu proyecto
  - 
    title: Comparte
  - 
    title: '¿Qué sigue?'
