---
title: Nie wpadnij!
hero_image: images/banner.png
description: Zaprojektujesz i zbudujesz grę parkour z widokiem z góry, z przeszkodą lub platformą.
meta_title: Projekty programistyczne Scratcha dla dzieci i młodzieży | Nie wpadnij
meta_description: Naucz się języka Scratch dzięki projektom programistycznym Fundacji Raspberry Pi dla dzieci i młodzieży. Stwórz grę parkour w Scratchu, a następnie skacz, podskakuj lub lataj, aby złapać przejażdżkę.
version: 4
listed: true
copyedit: false
last_tested: "2021-03-26"
steps:
  - 
    title: Co będziesz robić
  - 
    title: Wybierz swój motyw
  - 
    title: Skacz, podskakuj, odbijaj się lub szybuj!
    completion:
      - engaged
  - 
    title: Zwycięzca
  - 
    title: Jeździj na platformach
  - 
    title: Dostosuj poziom trudności
    completion:
      - internal
  - 
    title: Szybki quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Ulepsz swój projekt
  - 
    title: Udostępnij
  - 
    title: Co dalej?
