---
title: Ne tombe pas dedans !
hero_image: images/banner.png
description: Concevoir et créer un obstacle en vue de dessus ou un jeu de parcours de plateforme.
meta_title: Scratch coding projects for kids and teens | Don't fall in
meta_description: Learn Scratch with the Raspberry Pi Foundation’s coding projects for kids and teens. Make a Scratch parkour game then jump, hop, or fly to catch a ride.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: What you will make
  - 
    title: Choisir ton thème
  - 
    title: Saute, bondis, rebondis ou glisse !
    completion:
      - engaged
  - 
    title: Gagnant
  - 
    title: Monter sur des plateformes
  - 
    title: Ajuster la difficulté
    completion:
      - internal
  - 
    title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Challenge
    challenge: true
  - 
    title: Partager
  - 
    title: Et ensuite ?
